# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TaskPrioritizingStrategyDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TaskPrioritizingStrategyDemo
	pod 'Masonry'
  pod 'YYKit'
  pod 'TaskPrioritizingStrategy', :path => '../TaskPrioritizingStrategy.podspec'

end
